### ISSUE TITLE
add requirement if needed

### ISSUE THREAD

**Issue by hariszaf** [SysBioengLab/looplessFluxSampler#3]
https://github.com/SysBioengLab/looplessFluxSampler/blob/640b664e31a4ce4e2ccfc243284d6daededbfe74/README.md?plain=1#L2

Hi all! 

@psaahiguera I made it and I was able to run `example1.m`.
Yet, I had to install the *Statistics and Machine Learning Toolbox* in order to enable the `randsample` function used in the `ADSB` case. 

If that is the case maybe it would be better to add it in the README or find an alternative way so it's not required? 

In any case, thanks for the great algo! :muscle:

**Comment by psaahiguera** [comment]
Hi Haris,

Thank you for raising this issue. This has been fixed now. There is no need to employ the Statistics and Machine Learning Toolbox ;)

Regards

Pedro
